name: codio-publish
on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cleanup
        run: rm -rf .git

      - name: Publish to Codio
        uses: codio/codio-assignment-publish-action@master
        with:
          client-id: ${{ secrets.CODIO_PRODUCTION_CLIENT_ID }}
          secret-id: ${{ secrets.CODIO_PRODUCTION_SECRET_ID }}
          dir: ./
          course-id: d5acfd16bb506a5b03c95cef3399e1d4
          assignment-id: 3b5265189ac846a128a6cd19a4b869b8
          changelog: ${{ github.event.head_commit.message }}
          domain: codio.com